[workspace]
channels = ["conda-forge"]
name = "WFChemCookbook"
platforms = ["linux-64", "linux-aarch64", "osx-64", "osx-arm64", "win-64"]
version = "0.1.0"

[environments]
python-310 = ["python-310"]
python-311 = ["python-311"]
python-312 = ["python-312"]
python-313 = ["python-313"]
python-314 = ["python-314"]
dev = ["dev", "doc"]

[dependencies]
matplotlib = ">=3.10.8,<4"
numpy = ">=2.2.6,<3"
pandas = ">=2.3.3,<3"
pip = ">=25.0,<26"
python = "*"
rdkit = ">=2025.9.4,<2026"
seaborn = ">=0.13.2,<0.14"

# [pypi-dependencies]
# jcamp = ">=1,<2"

[feature.python-310.dependencies]
python = "3.10.*"

[feature.python-311.dependencies]
python = "3.11.*"

[feature.python-312.dependencies]
python = "3.12.*"

[feature.python-313.dependencies]
python = "3.13.*"

[feature.python-314.dependencies]
python = "3.14.*"

[feature.dev.dependencies]
jupyterlab = ">=4.3.4,<5"
nbclient = "*"
pixi-kernel = "*"
pip = "*"
conda = "*"

[feature.doc.dependencies]
jupytext = "*"
jupyter-book = "*"
ipykernel = "*"
myst-parser = "*"
myst-nb = "*"
mystmd = "*"

[feature.doc.tasks]
build = "cd book && myst build --execute --strict --check-links"
serve = "cd book && jupyter-book start "
clean = "cd book && rm -rf _build"
